name: linux-x64
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test262:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y libcppunit-dev cmake
      - run: git clone --recurse-submodules https://github.com/openwebf/quickjs
      - run: ls -lah
      - run: cd quickjs && bash scripts/ci.sh
      - run: cd quickjs && cat test262_report.txt
      - run: cd quickjs && cat test262_errors.txt
